version: '3.8'

volumes:
  pgdata:

services:
  app:
    tty: true
    build: .
    stdin_open: true
    command: "rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      RAILS_DB_HOST: db
      RAILS_DB_NAME: greenatom
      RAILS_DB_USER: greenatom
      RAILS_DB_PASS: greenatom123
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: greenatom
      POSTGRES_USER: greenatom
      POSTGRES_PASSWORD: greenatom123
